version: "2.23"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"